package Model;
// Generated 17/08/2017 09:01:23 PM by Hibernate Tools 4.3.1


import Model.Cliente;
import java.util.HashSet;
import java.util.Set;

/**
 * Catgenero generated by hbm2java
 */
public class Catgenero  implements java.io.Serializable {


     private String idGenero;
     private String genero;
     private Set<Cliente> clientes = new HashSet<Cliente>(0);

    public Catgenero() {
    }

	
    public Catgenero(String idGenero) {
        this.idGenero = idGenero;
    }
    public Catgenero(String idGenero, String genero, Set<Cliente> clientes) {
       this.idGenero = idGenero;
       this.genero = genero;
       this.clientes = clientes;
    }
   
    public String getIdGenero() {
        return this.idGenero;
    }
    
    public void setIdGenero(String idGenero) {
        this.idGenero = idGenero;
    }
    public String getGenero() {
        return this.genero;
    }
    
    public void setGenero(String genero) {
        this.genero = genero;
    }
    public Set<Cliente> getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set<Cliente> clientes) {
        this.clientes = clientes;
    }




}


