package Model;
// Generated 13/08/2017 06:13:12 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private Integer idEmpleado;
     private Empleado empleado;
     private Empresa empresa;
     private Persona persona;
     private Rol rol;
     private Sucursal sucursal;
     private Date fechaRegistro;
     private Date fechaIngreso;
     private Date fechaBaja;
     private String claveEmpleado;
     private String correoElectronico;
     private Integer telefono1;
     private Integer telefono2;
     private String status;
     private byte[] foto;
     private String contrasena;
     private Set<Empleado> empleados = new HashSet<Empleado>(0);

    public Empleado() {
    }

	
    public Empleado(Empresa empresa, Persona persona, Rol rol, Sucursal sucursal, Date fechaRegistro, Date fechaIngreso, String status) {
        this.empresa = empresa;
        this.persona = persona;
        this.rol = rol;
        this.sucursal = sucursal;
        this.fechaRegistro = fechaRegistro;
        this.fechaIngreso = fechaIngreso;
        this.status = status;
    }
    public Empleado(Empleado empleado, Empresa empresa, Persona persona, Rol rol, Sucursal sucursal, Date fechaRegistro, Date fechaIngreso, Date fechaBaja, String claveEmpleado, String correoElectronico, Integer telefono1, Integer telefono2, String status, byte[] foto, String contrasena, Set<Empleado> empleados) {
       this.empleado = empleado;
       this.empresa = empresa;
       this.persona = persona;
       this.rol = rol;
       this.sucursal = sucursal;
       this.fechaRegistro = fechaRegistro;
       this.fechaIngreso = fechaIngreso;
       this.fechaBaja = fechaBaja;
       this.claveEmpleado = claveEmpleado;
       this.correoElectronico = correoElectronico;
       this.telefono1 = telefono1;
       this.telefono2 = telefono2;
       this.status = status;
       this.foto = foto;
       this.contrasena = contrasena;
       this.empleados = empleados;
    }
   
    public Integer getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(Integer idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
    public Sucursal getSucursal() {
        return this.sucursal;
    }
    
    public void setSucursal(Sucursal sucursal) {
        this.sucursal = sucursal;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    public Date getFechaBaja() {
        return this.fechaBaja;
    }
    
    public void setFechaBaja(Date fechaBaja) {
        this.fechaBaja = fechaBaja;
    }
    public String getClaveEmpleado() {
        return this.claveEmpleado;
    }
    
    public void setClaveEmpleado(String claveEmpleado) {
        this.claveEmpleado = claveEmpleado;
    }
    public String getCorreoElectronico() {
        return this.correoElectronico;
    }
    
    public void setCorreoElectronico(String correoElectronico) {
        this.correoElectronico = correoElectronico;
    }
    public Integer getTelefono1() {
        return this.telefono1;
    }
    
    public void setTelefono1(Integer telefono1) {
        this.telefono1 = telefono1;
    }
    public Integer getTelefono2() {
        return this.telefono2;
    }
    
    public void setTelefono2(Integer telefono2) {
        this.telefono2 = telefono2;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public byte[] getFoto() {
        return this.foto;
    }
    
    public void setFoto(byte[] foto) {
        this.foto = foto;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public Set<Empleado> getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set<Empleado> empleados) {
        this.empleados = empleados;
    }




}


