package Model;
// Generated 17/08/2017 09:01:23 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pais generated by hbm2java
 */
public class Pais  implements java.io.Serializable {


     private String idPais;
     private String pais;
     private Set<Persona> personas = new HashSet<Persona>(0);

    public Pais() {
    }

	
    public Pais(String idPais) {
        this.idPais = idPais;
    }
    public Pais(String idPais, String pais, Set<Persona> personas) {
       this.idPais = idPais;
       this.pais = pais;
       this.personas = personas;
    }
   
    public String getIdPais() {
        return this.idPais;
    }
    
    public void setIdPais(String idPais) {
        this.idPais = idPais;
    }
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }
    public Set<Persona> getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set<Persona> personas) {
        this.personas = personas;
    }




}


