package Model;
// Generated 17/08/2017 09:01:23 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private String rfcPersona;
     private Pais pais;
     private String nombre;
     private String apellidoPaterno;
     private String apellidoMaterno;
     private String correoElectronico;
     private Date fechaNacimiento;
     private String estado;
     private String municipio;
     private String localidad;
     private String colonia;
     private Integer codigoPostal;
     private long telefono1;
     private Long telefono2;
     private String alias;
     private String genero;
     private String estadoCivil;
     private String nacionalidad;
     private String numeroSeguroSocial;
     private String numeroIne;
     private byte[] foto;
     private Set<Empleado> empleados = new HashSet<Empleado>(0);
     private Set<Empresa> empresas = new HashSet<Empresa>(0);

    public Persona() {
    }

	
    public Persona(String rfcPersona, String nombre, String apellidoPaterno, String apellidoMaterno, String correoElectronico, Date fechaNacimiento, long telefono1, String alias, String genero) {
        this.rfcPersona = rfcPersona;
        this.nombre = nombre;
        this.apellidoPaterno = apellidoPaterno;
        this.apellidoMaterno = apellidoMaterno;
        this.correoElectronico = correoElectronico;
        this.fechaNacimiento = fechaNacimiento;
        this.telefono1 = telefono1;
        this.alias = alias;
        this.genero = genero;
    }
    public Persona(String rfcPersona, Pais pais, String nombre, String apellidoPaterno, String apellidoMaterno, String correoElectronico, Date fechaNacimiento, String estado, String municipio, String localidad, String colonia, Integer codigoPostal, long telefono1, Long telefono2, String alias, String genero, String estadoCivil, String nacionalidad, String numeroSeguroSocial, String numeroIne, byte[] foto, Set<Empleado> empleados, Set<Empresa> empresas) {
       this.rfcPersona = rfcPersona;
       this.pais = pais;
       this.nombre = nombre;
       this.apellidoPaterno = apellidoPaterno;
       this.apellidoMaterno = apellidoMaterno;
       this.correoElectronico = correoElectronico;
       this.fechaNacimiento = fechaNacimiento;
       this.estado = estado;
       this.municipio = municipio;
       this.localidad = localidad;
       this.colonia = colonia;
       this.codigoPostal = codigoPostal;
       this.telefono1 = telefono1;
       this.telefono2 = telefono2;
       this.alias = alias;
       this.genero = genero;
       this.estadoCivil = estadoCivil;
       this.nacionalidad = nacionalidad;
       this.numeroSeguroSocial = numeroSeguroSocial;
       this.numeroIne = numeroIne;
       this.foto = foto;
       this.empleados = empleados;
       this.empresas = empresas;
    }
   
    public String getRfcPersona() {
        return this.rfcPersona;
    }
    
    public void setRfcPersona(String rfcPersona) {
        this.rfcPersona = rfcPersona;
    }
    public Pais getPais() {
        return this.pais;
    }
    
    public void setPais(Pais pais) {
        this.pais = pais;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidoPaterno() {
        return this.apellidoPaterno;
    }
    
    public void setApellidoPaterno(String apellidoPaterno) {
        this.apellidoPaterno = apellidoPaterno;
    }
    public String getApellidoMaterno() {
        return this.apellidoMaterno;
    }
    
    public void setApellidoMaterno(String apellidoMaterno) {
        this.apellidoMaterno = apellidoMaterno;
    }
    public String getCorreoElectronico() {
        return this.correoElectronico;
    }
    
    public void setCorreoElectronico(String correoElectronico) {
        this.correoElectronico = correoElectronico;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getMunicipio() {
        return this.municipio;
    }
    
    public void setMunicipio(String municipio) {
        this.municipio = municipio;
    }
    public String getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(String localidad) {
        this.localidad = localidad;
    }
    public String getColonia() {
        return this.colonia;
    }
    
    public void setColonia(String colonia) {
        this.colonia = colonia;
    }
    public Integer getCodigoPostal() {
        return this.codigoPostal;
    }
    
    public void setCodigoPostal(Integer codigoPostal) {
        this.codigoPostal = codigoPostal;
    }
    public long getTelefono1() {
        return this.telefono1;
    }
    
    public void setTelefono1(long telefono1) {
        this.telefono1 = telefono1;
    }
    public Long getTelefono2() {
        return this.telefono2;
    }
    
    public void setTelefono2(Long telefono2) {
        this.telefono2 = telefono2;
    }
    public String getAlias() {
        return this.alias;
    }
    
    public void setAlias(String alias) {
        this.alias = alias;
    }
    public String getGenero() {
        return this.genero;
    }
    
    public void setGenero(String genero) {
        this.genero = genero;
    }
    public String getEstadoCivil() {
        return this.estadoCivil;
    }
    
    public void setEstadoCivil(String estadoCivil) {
        this.estadoCivil = estadoCivil;
    }
    public String getNacionalidad() {
        return this.nacionalidad;
    }
    
    public void setNacionalidad(String nacionalidad) {
        this.nacionalidad = nacionalidad;
    }
    public String getNumeroSeguroSocial() {
        return this.numeroSeguroSocial;
    }
    
    public void setNumeroSeguroSocial(String numeroSeguroSocial) {
        this.numeroSeguroSocial = numeroSeguroSocial;
    }
    public String getNumeroIne() {
        return this.numeroIne;
    }
    
    public void setNumeroIne(String numeroIne) {
        this.numeroIne = numeroIne;
    }
    public byte[] getFoto() {
        return this.foto;
    }
    
    public void setFoto(byte[] foto) {
        this.foto = foto;
    }
    public Set<Empleado> getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set<Empleado> empleados) {
        this.empleados = empleados;
    }
    public Set<Empresa> getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Set<Empresa> empresas) {
        this.empresas = empresas;
    }




}


