package Model;
// Generated 17/08/2017 09:01:23 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Rol generated by hbm2java
 */
public class Rol  implements java.io.Serializable {


     private RolId id;
     private Empresa empresa;
     private String rol;
     private String descripcion;
     private Set<Empleado> empleados = new HashSet<Empleado>(0);

    public Rol() {
    }

	
    public Rol(RolId id, Empresa empresa, String rol, String descripcion) {
        this.id = id;
        this.empresa = empresa;
        this.rol = rol;
        this.descripcion = descripcion;
    }
    public Rol(RolId id, Empresa empresa, String rol, String descripcion, Set<Empleado> empleados) {
       this.id = id;
       this.empresa = empresa;
       this.rol = rol;
       this.descripcion = descripcion;
       this.empleados = empleados;
    }
   
    public RolId getId() {
        return this.id;
    }
    
    public void setId(RolId id) {
        this.id = id;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public String getRol() {
        return this.rol;
    }
    
    public void setRol(String rol) {
        this.rol = rol;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Empleado> getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set<Empleado> empleados) {
        this.empleados = empleados;
    }




}


