package Model;
// Generated 17/08/2017 09:01:23 PM by Hibernate Tools 4.3.1



/**
 * RolId generated by hbm2java
 */
public class RolId  implements java.io.Serializable {


     private int idRol;
     private int idEmpresa;

    public RolId() {
    }

    public RolId(int idRol, int idEmpresa) {
       this.idRol = idRol;
       this.idEmpresa = idEmpresa;
    }
   
    public int getIdRol() {
        return this.idRol;
    }
    
    public void setIdRol(int idRol) {
        this.idRol = idRol;
    }
    public int getIdEmpresa() {
        return this.idEmpresa;
    }
    
    public void setIdEmpresa(int idEmpresa) {
        this.idEmpresa = idEmpresa;
    }




}


